### ISSUE TITLE
Main operating base

### ISSUE THREAD

**Issue by Gabykhan** [132nd-vWing/TRMA#13]
Given the initial "high fidelity area" advertised at release, it might be necessary to consider a first main operating base within this area, or very close to it, so that we mostly play in this airspace.
![6631c92fe2bfa.jpg](https://github.com/132nd-vWing/TRMA/assets/141456266/3aaaaa3b-c314-4efc-89e6-721125e96114)

I found it difficult to find interesting targets in the low resolution areas of the PG map.

**Comment by Shadoga** [comment]
Shadow here.
In this case the only option with enough spawnpoints and maneuvering areas would be Rovaniemi.
Plus, the Gulf of Bothnia south of Rovaniemi leaves almost no maneuvering space for the carrier.

**Comment by Gabykhan** [comment]
I guess the map doesn't abruptly ends there on the south. The sea is the sea, I don't think it will be an issue to find a 30 Nm area to place the carrier down there.

**Comment by hbjonsson** [comment]
I think we should get accustomed to whatever MOB we will be operating out of initially, e.g. Bodo. Its detailed enough.
Spawnpoints are not restrictive as you can use "start from ground" ( would recommend that anyway).

Rovainemi is way to far away from the Atlantic for the Navy guys also.

**Comment by Gabykhan** [comment]
The issue is not the airfield itself, but the surroundings. If we need to fly to the other side of the map to find an interesting target area, it's counterproductive.
Regarding moving from one airbase to another, there's really no issue I believe. Being able to reposit without major issue is definitely a skill that all aviators need to master. Be it to take part into a major exercise abroad, or to wage war at the other side of the world.
