### ISSUE TITLE
Tanker freqs on VHF or UHF?

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/TRMA#16]
Should we have tankers on VHF or UHF?

**Comment by hbjonsson** [comment]
I´d say UHF.  All platform´s who tank can support a UHF frequency on their **primary radio**, this will avoid having to have aircraft do the radio dance should they be using their secondary for intra-flight on either UHF or VHF as the case may be.

**Comment by Gabykhan** [comment]
IRL NATO tankers are on UHF frequencies. That's not a reason not to use VHF, but it means that all NATO aircraft are capable of doing AAR operations solely on UHF.

**Comment by Shadoga** [comment]
UHF.

**Comment by 132Typhoon** [comment]
UHF

**Comment by 132ndNeck** [comment]
I have no strong oppinion here. Advantage with VHF is to be able to keep UHF free to listen to AWACS/tactical comms while refueling. But also no problem shifting all tankers to UHF completely.

**Comment by 132ndNeck** [comment]
Based on the dicussion and input, we set this to decided and will use UHF freqs for tankers.
