### ISSUE TITLE
Scripting request: Tanker activation/deactivation

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/TRMA#27]
@132nd-Entropy 
I have added 11 tankers (all set to late activation), see screenshot below. All tankers set with correct tacan, callsign and frequency. The only thing missing is moving them to the correct track (not yet decided where).

Can you help with implementing a F10 menu for activating the tankers? Also, if possible add an F10 menu for deactivating the tanker when it has been activated

![bilde](https://github.com/132nd-vWing/TRMA/assets/26002570/b4d0eb36-12f0-429f-8248-05388241bc15)

**Comment by 132ndNeck** [comment]
Worked as intended. Also great with the new option to see the active tankers listed in F10.
Thanks for the help!

**Comment by 132nd-Entropy** [comment]
some thought, what if a tanker gets destroyed. I'd have to modify the script else the 'list active tanker' function wont be correct anymore. I can either do that, or set the tankers to invulnerable, which you prefer?

**Comment by 132ndEvo** [comment]
Should we set the tanker to invulnerable and unlimited fuel?

**Comment by 132nd-Entropy** [comment]
Unlimited fuel is already set. As I said we can either set them to invulnerable, or simply you spawn a new one when the old one gets damaged

**Comment by 132ndNeck** [comment]
> some thought, what if a tanker gets destroyed. I'd have to modify the script else the 'list active tanker' function wont be correct anymore. I can either do that, or set the tankers to invulnerable, which you prefer?

I suggest we keep them so they can be damaged. That way, we do not enfore any negative training (if messing up with the tanker, then having the tanker crash is a good indication that you did something wrong).  So ideally I think it is best if the "list active tanker list" gets updated. 

As long as we can spawn a new tanker, this should not interfere with anyones training (except the pilot that does the damage). So I would suggets to keep it.

**Comment by 132nd-Entropy** [comment]
agreed!

**Comment by 132ndNeck** [comment]
@132nd-Entropy 
I have added two additional tankers in centre of range 22:
AR503 #IFF:5503FR     (ARCO 6)
AR403 #IFF:5403FR     (SHELL 7)

Can you add them to the script so they can be activated same as the other tankers?
