### ISSUE TITLE
Scripting request: Missile script

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/TRMA#29]
@132nd-Entropy:
Request to implement the missile script similar to what we have in ATRM.

**Comment by 132ndNeck** [comment]
Missile script works great.

But, is it possible to add a sound notification like we had on ATRM? This will make it easier for pilots to realize that they are hit.

**Comment by 132ndNeck** [comment]
> sure, Im going to implement this. However, there is no way to specifically send a text message or sound to a unit. It all works on the GROUP level. As such, when there is groups with more than one client all clients in that group will hear that sound.

Ah, I was not aware. That is weird, since in the ME, there is a option to use sound to unit?
![image](https://github.com/user-attachments/assets/a99949fb-fd34-411c-a454-0284a3d55a81)

**Comment by 132nd-Entropy** [comment]
Yeah but not in scripting. It's the old thing that's why it is recommended not to have groups with more than one unit, because the entire messaging menu etc system works on a group level.
