### ISSUE TITLE
New CV Ops Frequencies 

### ISSUE THREAD

**Issue by 132ndEvo** [132nd-vWing/TRMA#33]
Hello, would it be possible to add the following frequencies for the new training mission?
Land/Launch
Departure
Strike
Red Crown
Approach Alpha
Approach Bravo
Airwing Common
Squadron Common (494th)
Squadron Common (108th)

It would be nice if the freqs were UHF but there is no requirement for the 494th. Can anyone from the 108th let us know what you need? Thanks

**Comment by 132nd-Entropy** [comment]
108th can do either UHF or VHF doesn't matter to us

**Comment by 132ndNeck** [comment]
@132ndEvo : What is the purpose of Strike, Red Crown and Airwing common n in the 132nd context?

**Comment by 132nd-Entropy** [comment]
I'd be happy with any implementation but I'd vote to keep it as simple as possible and as complicated as required only. 

Land/Launch  - I'd call this Tower, and I'd use the same freq as the AI carrier freq (lights). That would then hopefully finally get rid of the problem that we had on the PG map that traditionally half the guys are on 309.500 and the other half on 309.100 during startup

Departure   - do we really need that? Could we not use Marshall for both departure and arrival ? 
Strike   - we don't need that, I'd go for AWACS checkin after departure
Red Crown - whats that? AWACS? (see above)
Approach Alpha  - Marshall 
Approach Bravo  - Marshall
Airwing Common - not needed imo
Squadron Common (494th) - not needed imo
Squadron Common (108th) - not needed imo


so I'd do this

- 309.500 Tower (this includes LSO, AI Lights, all call on deck movement, all mandatory calls after INITIAL (which is called on Marshall Freq before switching to Tower on arrival and Kilo after departure)

-309.800 Marshall (all calls within 50nm of the boat, unless under Tower control)

thats all, only those two

ofc only my 0.02$

**Comment by Gabykhan** [comment]
In ATRM, we used for the carrier: AI ATC (Lights): 309.5 and Marshall: 309.9
As of today (30/09/2024), .0.0.1.74 miz gives for CVN-73 309.900 and MDC states: CVN-73 AI Tower P 309.9 and 127.5

_But_ current F-18 preset was done on the assumption that we would keep 309.500 for AI Tower and 309.900 for manned Approach frequency.

Can we reverse to ATRM carrier AI frequency, or otherwise we have to change all of Hornets preset... ?

Thanks

**Comment by 132nd-Entropy** [comment]
sure no problem

**Comment by 132nd-Entropy** [comment]
changing the freqs on the carrier is ofc super easy, but so far nobody (but me?) commented on the freqs so I think thats why there has not been any updates or changes also to the TRMA brief

**Comment by 132nd-Entropy** [comment]
closing this now, as we've discussed this.
