### ISSUE TITLE
Scripting request: AR in range 23

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/TRMA#42]
@132nd-Entropy  :
Would it be possible to script the following for range 23:

- Add the following in the F10 menu: (ability to activate and deactivate)

_Activate Range 23AR SCUD hunt_
This should turn on flag 40, which will activate the scenario.

- Add the following in the F10 menu: (ability to activate and deactivate)

_Activate Range 23 AR SCUD hunt IADS_
This should turn on flag 46 which will activate units and the script for the IADS.

**Comment by 132nd-Entropy** [comment]
done, only the menus that set the flags are implemented. so the scearios can be activated. if deactivation is needed, then we'd spawn them via script dynamically so I can also despawn them. I suggest to add this later and focus on the other things first ?

**Comment by 132ndNeck** [comment]
> done, only the menus that set the flags are implemented. so the scearios can be activated. if deactivation is needed, then we'd spawn them via script dynamically so I can also despawn them. I suggest to add this later and focus on the other things first ?

Yes, I agree. Let's focus on implementing a lot of options/ranges/scenarios now at the start so we have variation, and then we can work on cleaning it up after that

**Comment by 132ndNeck** [comment]
Working as intended
