### ISSUE TITLE
CVN-73 TACAN not working properly

### ISSUE THREAD

**Issue by 132nd-Astero** [132nd-vWing/TRMA#44]
Issue: unable to find CV TACAN when recovering
Date: 09/08/2024

About 1.5h after spawning and 10NM away from CV, we were unable to find CV TACAN.
Evo also confirmed that he did not find TACAN either. He assumes that it might be a bug with script.
Entropy thinks that it's an old bug and the scheduler needs to be put back in.

**Comment by 132ndNeck** [comment]
@132nd-Entropy Are you able to look into this?

**Comment by 132nd-Astero** [comment]
Thanks Entropy!
Entropy has fixed it and wrote on discord.
Didn't test yet, but 13X should be working now.
