### ISSUE TITLE
OH58D(R) CMWS missing

### ISSUE THREAD

**Issue by evilivan** [132nd-vWing/TRMA#50]
Please uncheck the "Install AN/ALQ-144 IRCM" option for OH58 Kiowa's - this option reverts to the older IR missile defence system and removes the more modern CMWS / flares system. Thanks :-)

Screengrab from editor:

![2024-09-23_10h39_26](https://github.com/user-attachments/assets/e293d47b-ec53-41da-9f65-333aca901f75)

**Comment by 132ndNeck** [comment]
Fixed in latest version .64
