### ISSUE TITLE
Scripting request - F10 activation of AWACS

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/TRMA#51]
@132nd-Entropy 
Can you add red AWACS to the F10 menu for activation:
FOCUS  (in range 22)
WIZARD  (in range 21)

**Comment by 132ndNeck** [comment]
@132nd-Entropy 
Can you also add the following to the BLUE AWACS F10 menu for activation:
DARKSTAR (Range 23)
OVERLORD (CVOA)

**Comment by 132nd-Entropy** [comment]
```local AWACSTemplates = {
  {name = "FOCUS #IFF:5602FR", spawnMenuText = "Spawn Red AWACS FOCUS", despawnMenuText = "Despawn Red AWACS FOCUS", menuGroup = "RED"},
  {name = "WIZARD #IFF:5601FR", spawnMenuText = "Spawn Red AWACS WIZARD", despawnMenuText = "Despawn Red AWACS WIZARD", menuGroup = "RED"},
  {name = "DARKSTAR #IFF:5612FR", spawnMenuText = "Spawn Blue AWACS Darkstar", despawnMenuText = "Despawn Blue AWACS Darkstar", menuGroup = "BLUE"},
  {name = "MAGIC #IFF:5611FR", spawnMenuText = "Spawn Blue AWACS MAGIC", despawnMenuText = "Despawn Blue AWACS MAGIC ", menuGroup = "BLUE"},
  {name = "OVERLORD 2 #IFF:5613FR", spawnMenuText = "Spawn Blue AWACS OVERLORD", despawnMenuText = "Despawn Blue AWACS OVERLORD", menuGroup = "BLUE"}
  }```


thats the templates we have, right now FOCUS and DARKSTAR are spawned by default, but they are all added to the menus and can be spawned, despawned and listed any time.

**Comment by 132ndNeck** [comment]
> on it, @132ndNeck just to confirm, those 4 are all awacs we have, right? Should any of them be spawned by default ? right now if I see it correctly FOCUS and DARKSTAR are spawned by default, WIZARD and OVERLORD need to be activated by F10, correct?

Great, thanks! No, I was thinking that the only AWACS that is on by default is MAGIC (in the centre of the map), and then have OVERLORD, FOCUS, WIZARD and DARKSTAR all be on request based on the needs. This to keep the load to a minimum and make sure only AWACS that are "needed" are loaded. 

I assume I can simply tick and untick the box in the ME for fixing this, and it will not mess up the script?

**Comment by 132nd-Entropy** [comment]
done, only Magic on by default
