### ISSUE TITLE
R14 TRONES Location

### ISSUE THREAD

**Issue by 000Ready000** [132nd-vWing/TRMA#55]
I was just checking Google Maps to locate the POI's for R14 but could not find TRONES. I did find Trones Skole, Tolla, at the same location. Is this an error in DCS?

**Comment by 132ndNeck** [comment]
You will see it in DCS and in CombatFlite:
![bilde](https://github.com/user-attachments/assets/1a6eed3e-c357-45de-95a5-8c2d28c53e32)
