### ISSUE TITLE
F-14B Frequencies TRMA

### ISSUE THREAD

**Issue by 59thLefty** [132nd-vWing/TRMA#59]
I've made a provisional frequency table for the capabilities of our jet, feel free to use it as you see fit. 
It is not yet in compliance with Evo's request, I've not seen it in the time of making
https://github.com/132nd-vWing/TRMA/issues/33

[TRMA Frequency and callsign master list _F14 test.xlsx](https://github.com/user-attachments/files/17377216/TRMA.Frequency.and.callsign.master.list._F14.test.xlsx)

![image](https://github.com/user-attachments/assets/c35d5fb4-d1f1-45b4-9b03-b8c7bec4fa6a)

**Comment by 132nd-Entropy** [comment]
implemented, latest pdf will be uploaded the TRMA Brief. closing this for now
