### ISSUE TITLE
Range 14 SAM's not working?

### ISSUE THREAD

**Issue by 000Ready000** [132nd-vWing/TRMA#60]
Yesterday I used R14 and activated the scenario. SA13's and SZU23's spawned but were not active, at least that is what it looked like. Other objects were active.

**Comment by 132ndNeck** [comment]
> Yesterday I used R14 and activated the scenario. SA13's and SZU23's spawned but were not active, at least that is what it looked like. Other objects were active.

Question: From your AAR, you say you might have killed them before you were in range for them to shoot you?
"It seemed the SA-13's did not become active, they spawned into the R14 scenario, but did not engage me. Or I stayed out of their WEZ and killed them before they could become active."

So, my question, before I spend time debugging and checking, do you know you were within range, and they should have fired at you, but it did not happen?

**Comment by 132nd-Entropy** [comment]
@000Ready000 did you see Neck's post? I just looked, the R14 scenario is activated via a ME flag, and the air defenses should spawn in. they are not set to inactive so I don't think thats on our end. Please re-test this and confirm if this is indeed a bug - which I doubt. 

@132ndNeck the flag can also be activated by a vehicle inside zone action. as we have this now via a F10 menu script, can that trigger (and the zone etc) be removed, as it takes resources?

**Comment by 132ndNeck** [comment]
> 
> @132ndNeck the flag can also be activated by a vehicle inside zone action. as we have this now via a F10 menu script, can that trigger (and the zone etc) be removed, as it takes resources?

Yes, now that we have it working via F10 menu it can be deleted (trigger zone alternative)

**Comment by 132nd-Entropy** [comment]
triggers removed, as it's set via script. as we didnt hear back from @000Ready000 , Im closing this
